version: 1.0.{build}
branches:
  only:
  - dev
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: artifacts/packages/release/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/alhardy/api/v2/package
  api_key:
    secure: gIAiACgNj+JzXyLLTe3rLxZyrAB9RpC8Lw81xEjdOLXqotprqEwGiFWRipEqkpps
  symbol_server: https://nuget.symbolsource.org/MyGet/alhardy
  artifact: artifacts/packages/release/*.nupkg
  on:
    branch: dev
